notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

before_script:
  - xmllint --version

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10


matrix:
  include:
    - os: linux
      env: ATOM_CHANNEL=stable
      language: node_js
      node_js: "5"
      sudo: required
      dist: trusty
      install:
        - sudo apt-get install libxml2-utils
    - os: linux
      env: ATOM_CHANNEL=beta
      language: node_js
      node_js: "5"
      sudo: required
      dist: trusty
      install:
        - sudo apt-get install libxml2-utils
    - os: osx
      env: ATOM_CHANNEL=stable
      language: node_js
      node_js: "5"
    - os: osx
      env: ATOM_CHANNEL=beta
      language: node_js
      node_js: "5"

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
